language: java
jdk:
  - openjdk11

sudo: false

env:
  matrix:
  - TERM=dumb
  global:
  - secure: gjT/7+UM+b++9QYenPDDB9WtiDpQWrIicWIsmgLTs8r2k7EYUQhc5es/UotE0snYN7jYYQPRusBQENRFZJq718msOdwdeU7Xid/Rc2pA25vuDdWNzn2lkrTNQDFf0BNQnwPWkKeWwWiw1QZwMwwLI7aazkBPMB66eZK1QCs2xHs=
  - secure: Uon5TCEqAqdtSChW4kd8ui8Ct8lWEPML/Q2I5+GWwKYQydIfIOrbNl3Xeu2Nh+Y2hWTIDm7N9FT63seKGZ44hBfmUxtsXBq1p4SSRwDcXMN9EYBCiJfHxwjNVkbgKzIy2lJ/JCR4fduadePOybVhvMhAW2oWDMyRJi4/rcBAsvg=
  - secure: Nrhyns2rgmS3PnoLsUUoqElUBMxw9cr4TBCe3zEA1ro7zr4+YL3uUis/UFlwsPVt0jIeTI7AQFVeggSgWwT8vnEZ5dnB1ZOlhIHWP6hiaij2000HAfuuam0fMhLoZtXFN+xZKSi5JuVxfAs5hjobkr5xQC52jHWNhy3DkLhdSFo=

# -PgithubUser="${GITHUB_TOKEN}" -PgithubPassword="" -PjfrogUser="${JFROG_USER}" -PjfrogPassword="${JFROG_PASSWORD}" --stacktrace

script: mvn install test
